import { useState, useEffect } from 'react';
import { Brain, TrendingUp, Users, Newspaper, AlertCircle } from 'lucide-react';

interface AIInsightsProps {
  location: string;
}

export default function AIInsights({ location }: AIInsightsProps) {
  const [insights, setInsights] = useState<any>(null);
  const [news, setNews] = useState<any[]>([]);
  const [experts, setExperts] = useState<any[]>([]);
  const [crowdReports, setCrowdReports] = useState<any>(null);
  const [trends, setTrends] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAIData();
  }, [location]);

  const fetchAIData = async () => {
    try {
      setLoading(true);
      const [insightsRes, newsRes, expertsRes, crowdRes, trendsRes] = await Promise.all([
        fetch(`http://127.0.0.1:8000/api/weather/ai/insights?location=${location}`),
        fetch(`http://127.0.0.1:8000/api/weather/ai/news?location=${location}`),
        fetch(`http://127.0.0.1:8000/api/weather/ai/experts?location=${location}`),
        fetch(`http://127.0.0.1:8000/api/weather/ai/crowd-reports?location=${location}`),
        fetch(`http://127.0.0.1:8000/api/weather/ai/trends`)
      ]);

      const [insightsData, newsData, expertsData, crowdData, trendsData] = await Promise.all([
        insightsRes.json(),
        newsRes.json(),
        expertsRes.json(),
        crowdRes.json(),
        trendsRes.json()
      ]);

      setInsights(insightsData);
      setNews(newsData.news || []);
      setExperts(expertsData.experts || []);
      setCrowdReports(crowdData);
      setTrends(trendsData);
    } catch (error) {
      console.error('Error fetching AI data:', error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-lg">
        <div className="flex items-center gap-2 mb-4">
          <Brain className="text-purple-500" size={24} />
          <h2 className="text-xl font-bold dark:text-white">AI Intelligence</h2>
        </div>
        <p className="text-gray-600 dark:text-gray-400">Learning from online sources...</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* AI-Powered Insights */}
      <div className="bg-gradient-to-br from-purple-500 to-indigo-600 p-6 rounded-xl shadow-lg text-white">
        <div className="flex items-center gap-2 mb-4">
          <Brain size={24} />
          <h2 className="text-xl font-bold">AI-Powered Insights</h2>
        </div>
        {insights?.insights && (
          <div className="space-y-2">
            {insights.insights.map((insight: string, index: number) => (
              <div key={index} className="bg-white/10 backdrop-blur-sm p-3 rounded-lg">
                <p className="text-sm">{insight}</p>
              </div>
            ))}
          </div>
        )}
        <div className="mt-4 text-xs opacity-75">
          Generated by AI • {insights?.generated_by === 'ai' ? 'Enhanced with GPT-4' : 'Basic Analysis'}
        </div>
      </div>

      {/* Weather News */}
      <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-lg">
        <div className="flex items-center gap-2 mb-4">
          <Newspaper className="text-blue-500" size={24} />
          <h2 className="text-xl font-bold dark:text-white">Latest Weather News</h2>
        </div>
        <div className="space-y-4">
          {news.slice(0, 3).map((article, index) => (
            <div key={index} className="border-l-4 border-blue-500 pl-4 py-2">
              <h3 className="font-semibold text-gray-900 dark:text-white">{article.title}</h3>
              <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">{article.summary}</p>
              <div className="flex items-center gap-4 mt-2 text-xs text-gray-500">
                <span>{article.source}</span>
                <span>Relevance: {(article.relevance * 100).toFixed(0)}%</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Expert Predictions */}
      <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-lg">
        <div className="flex items-center gap-2 mb-4">
          <TrendingUp className="text-green-500" size={24} />
          <h2 className="text-xl font-bold dark:text-white">Expert Predictions</h2>
        </div>
        <div className="space-y-4">
          {experts.map((expert, index) => (
            <div key={index} className="bg-gray-50 dark:bg-gray-700 p-4 rounded-lg">
              <div className="flex items-start justify-between mb-2">
                <div>
                  <p className="font-semibold text-gray-900 dark:text-white">{expert.expert}</p>
                  <p className="text-xs text-gray-600 dark:text-gray-400">{expert.organization}</p>
                  <p className="text-xs text-blue-600 dark:text-blue-400 mt-1">{expert.specialization}</p>
                </div>
                <div className="text-right">
                  <span className="text-xs bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200 px-2 py-1 rounded">
                    {(expert.confidence * 100).toFixed(0)}% Confidence
                  </span>
                </div>
              </div>
              <p className="text-sm text-gray-700 dark:text-gray-300 mt-2">{expert.prediction}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Crowd-Sourced Reports */}
      <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-lg">
        <div className="flex items-center gap-2 mb-4">
          <Users className="text-orange-500" size={24} />
          <h2 className="text-xl font-bold dark:text-white">Live Community Reports</h2>
        </div>
        {crowdReports && (
          <>
            <div className="mb-4 flex flex-wrap gap-2">
              {crowdReports.trending_conditions?.map((condition: string, index: number) => (
                <span key={index} className="bg-orange-100 dark:bg-orange-900 text-orange-800 dark:text-orange-200 px-3 py-1 rounded-full text-sm">
                  #{condition}
                </span>
              ))}
            </div>
            <div className="space-y-3">
              {crowdReports.crowd_sourced?.map((report: any, index: number) => (
                <div key={index} className="flex items-start gap-3 bg-gray-50 dark:bg-gray-700 p-3 rounded-lg">
                  <AlertCircle className="text-orange-500 flex-shrink-0 mt-1" size={16} />
                  <div className="flex-1">
                    <p className="text-sm text-gray-900 dark:text-white">{report.report}</p>
                    <div className="flex items-center gap-3 mt-2 text-xs text-gray-500">
                      <span>{report.location}</span>
                      <span className={`px-2 py-0.5 rounded ${
                        report.verification === 'high' ? 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200' :
                        report.verification === 'moderate' ? 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200' :
                        'bg-gray-100 text-gray-800 dark:bg-gray-600 dark:text-gray-200'
                      }`}>
                        {report.verification} verification
                      </span>
                      <span>{new Date(report.timestamp).toLocaleTimeString()}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
            <div className="mt-4 text-sm text-gray-600 dark:text-gray-400">
              {crowdReports.total_reports} total reports from the community
            </div>
          </>
        )}
      </div>

      {/* Trending Topics */}
      {trends && (
        <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-lg">
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp className="text-pink-500" size={24} />
            <h2 className="text-xl font-bold dark:text-white">Trending Weather Topics</h2>
          </div>
          <div className="space-y-3">
            {trends.trending_topics?.map((topic: any, index: number) => (
              <div key={index} className="flex items-center justify-between bg-gray-50 dark:bg-gray-700 p-3 rounded-lg">
                <div className="flex-1">
                  <p className="font-semibold text-gray-900 dark:text-white">{topic.topic}</p>
                  <p className="text-xs text-gray-600 dark:text-gray-400 mt-1">{topic.mentions.toLocaleString()} mentions</p>
                </div>
                <span className={`px-3 py-1 rounded-full text-xs font-medium ${
                  topic.sentiment === 'concern' ? 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200' :
                  topic.sentiment === 'alert' ? 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200' :
                  'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200'
                }`}>
                  {topic.sentiment}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
