from typing import Dict, List
from datetime import datetime
import json


class DataExportService:
    """Weather data export functionality"""
    
    async def export_to_json(self, weather_data: Dict, forecast_data: List[Dict], filename: str = None) -> Dict:
        """Export weather data to JSON"""
        
        if not filename:
            filename = f"weather_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        
        export_data = {
            "export_date": datetime.now().isoformat(),
            "current_weather": weather_data,
            "forecast": forecast_data,
            "generated_by": "AI Weather Assistant"
        }
        
        return {
            "filename": filename,
            "format": "json",
            "data": json.dumps(export_data, indent=2),
            "size": len(json.dumps(export_data))
        }
    
    async def export_to_csv(self, forecast_data: List[Dict], filename: str = None) -> Dict:
        """Export forecast data to CSV"""
        
        if not filename:
            filename = f"weather_forecast_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        
        csv_lines = ["Date,Temperature,Description,Humidity,Wind Speed,Pressure"]
        
        for day in forecast_data:
            line = f"{day.get('date', '')},{day.get('temperature', '')},{day.get('description', '')},{day.get('humidity', '')},{day.get('wind_speed', '')},{day.get('pressure', '')}"
            csv_lines.append(line)
        
        csv_content = "\n".join(csv_lines)
        
        return {
            "filename": filename,
            "format": "csv",
            "data": csv_content,
            "size": len(csv_content)
        }
    
    async def generate_pdf_report(self, location: str, weather_data: Dict, forecast_data: List[Dict], 
                                 analysis: Dict = None, filename: str = None) -> Dict:
        """Generate comprehensive PDF weather report"""
        
        if not filename:
            filename = f"weather_report_{location}_{datetime.now().strftime('%Y%m%d')}.pdf"
        
        # In production: use reportlab or weasyprint to generate actual PDF
        report = {
            "filename": filename,
            "format": "pdf",
            "title": f"Weather Report - {location}",
            "report_date": datetime.now().isoformat(),
            "sections": {
                "summary": f"Current conditions in {location}: {weather_data.get('description', 'N/A')} at {weather_data.get('temperature', 'N/A')}°C",
                "current_conditions": weather_data,
                "forecast": forecast_data[:7],  # 7-day forecast
                "analysis": analysis or {"trend": "stable", "outlook": "Normal conditions"}
            },
            "charts": [
                {"type": "temperature_line", "title": "7-Day Temperature Trend"},
                {"type": "precipitation_bar", "title": "Daily Precipitation Forecast"},
                {"type": "wind_speed", "title": "Wind Speed Overview"}
            ],
            "watermark": "Generated by AI Weather Assistant"
        }
        
        return report
    
    async def schedule_export(self, user_id: str, export_config: Dict) -> Dict:
        """Schedule automatic exports for user"""
        
        schedule = {
            "user_id": user_id,
            "export_type": export_config.get("type", "json"),  # json, csv, pdf
            "frequency": export_config.get("frequency", "weekly"),  # daily, weekly, monthly
            "recipients": export_config.get("recipients", []),
            "created_at": datetime.now().isoformat(),
            "next_export": datetime.now().isoformat(),
            "enabled": True
        }
        
        return {
            "success": True,
            "message": "Export scheduled successfully",
            "schedule": schedule
        }
    
    async def get_export_history(self, user_id: str) -> List[Dict]:
        """Get user's export history"""
        
        # In production: retrieve from database
        history = [
            {
                "export_id": "exp_1",
                "type": "pdf",
                "filename": "weather_report_London_20260117.pdf",
                "size": "2.4 MB",
                "created_at": datetime.now().isoformat(),
                "location": "London"
            },
            {
                "export_id": "exp_2",
                "type": "csv",
                "filename": "weather_forecast_20260117_154232.csv",
                "size": "45 KB",
                "created_at": datetime.now().isoformat(),
                "location": "London"
            }
        ]
        
        return history
